name: ci

on:
  push:
    branches:
      - trunk
  pull_request:

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go: ["1.18"]
        os: [ubuntu-latest]
    name: Go ${{ matrix.go }} in ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}
    - name: Environment
      run: |
        go version
        go env
    - name: Install tools
      env:
        GO111MODULE: on
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.45.2
        golangci-lint --version
    - name: Lint
      run: |
        go mod tidy
        golangci-lint run ./... -v
    - name: Test
      env:
        GOFLAGS: -mod=mod
      run: go test -race -coverpkg=./... -coverprofile=coverage.txt ./...
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
